version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db
  server:
    build: .
    container_name: todo_api
    ports:
      - '8000:3000'
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/todo_db
    volumes:
      - .:/usr/src/app
    command: npm start
volumes:
  mongo_data:
